# Generated by Django 4.2.3 on 2023-07-23 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmaster', '0004_remove_activity_actual_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='status',
            field=models.CharField(choices=[('NEW', 'new'), ('INPROGRESS', 'in-progress'), ('COMPLETED', 'completed')], default=1, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('NEW', 'new'), ('INPROGRESS', 'in-progress'), ('COMPLETED', 'completed')], default=1, max_length=20, null=True),
        ),
    ]
